// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5btvZxwSNYojLQyuKnR_abhYLxNtPEI',
    appId: '1:131535253776:web:2b71307932bf39e0eb7595',
    messagingSenderId: '131535253776',
    projectId: 'new-curd-62c6e',
    authDomain: 'new-curd-62c6e.firebaseapp.com',
    storageBucket: 'new-curd-62c6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwB9Z3cEbH0MTwq2_2VcJhHhdUejXMIbw',
    appId: '1:131535253776:android:1a34bf60e4e24653eb7595',
    messagingSenderId: '131535253776',
    projectId: 'new-curd-62c6e',
    storageBucket: 'new-curd-62c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnze-2i4VMXZ4Hiqxlhaa1wTH-vOnABOQ',
    appId: '1:131535253776:ios:d0fc889fd3ebb0b1eb7595',
    messagingSenderId: '131535253776',
    projectId: 'new-curd-62c6e',
    storageBucket: 'new-curd-62c6e.appspot.com',
    iosClientId: '131535253776-i0l9rni4nd5dvsrklm0u5q4eajgqihvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiCal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnze-2i4VMXZ4Hiqxlhaa1wTH-vOnABOQ',
    appId: '1:131535253776:ios:d0fc889fd3ebb0b1eb7595',
    messagingSenderId: '131535253776',
    projectId: 'new-curd-62c6e',
    storageBucket: 'new-curd-62c6e.appspot.com',
    iosClientId: '131535253776-i0l9rni4nd5dvsrklm0u5q4eajgqihvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiCal',
  );
}
